export const NAVAL_BARANGAYS = [
  'Agpangi',
  'Anislagan',
  'Atipolo',
  'Borac',
  'Cabungaan',
  'Calumpang',
  'Capiñahan',
  'Caraycaray',
  'Catmon',
  'Haguikhikan',
  'Imelda',
  'Larrazabal',
  'Libertad',
  'Libtong',
  'Lico',
  'Lucsoon',
  'Mabini',
  'Padre Inocentes García (Pob.)',
  'Padre Sergio Eamiguel',
  'Sabang',
  'San Pablo',
  'Santo Niño',
  'Santissimo Rosario (Pob.)',
  'Talustusan',
  'Villa Caneja',
  'Villa Consuelo',
] as const;

export type NavalBarangay = typeof NAVAL_BARANGAYS[number];
